<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputPath>$(RELOADEDIIMODS)/p3ppc.multipleweapons</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="ModConfig.json"><CopyToOutputDirectory>Always</CopyToOutputDirectory></Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Reloaded.Memory" Version="8.0.1" />
    <PackageReference Include="Reloaded.Memory.SigScan.ReloadedII.Interfaces" Version="1.2.0" />
    <PackageReference Include="Reloaded.Mod.Interfaces" Version="2.4.0" ExcludeAssets="runtime" />
    <PackageReference Include="Reloaded.SharedLib.Hooks" Version="1.9.0" />
  </ItemGroup>
</Project>
